# Generated by Django 4.0.6 on 2022-07-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('urls', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ShopifyScrapper.url')),
                ('web_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_type', to='ShopifyScrapper.storetype')),
            ],
        ),
    ]
