# Generated by Django 4.0.6 on 2022-07-23 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('retailer', models.CharField(max_length=30)),
                ('product_type', models.CharField(max_length=20, null=True)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('store_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=30, null=True)),
                ('featured_image', models.CharField(max_length=150, null=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopifyScrapper.data')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('website', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopifyScrapper.website')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ShopifyScrapper.data')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopifyScrapper.website'),
        ),
    ]
