# Generated by Django 4.0.6 on 2022-07-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyScrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='urls',
        ),
    ]
