# Generated by Django 4.0.6 on 2022-07-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyScrapper', '0003_website_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='urls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ShopifyScrapper.url'),
        ),
    ]
