# Generated by Django 4.0.6 on 2022-07-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyScrapper', '0004_alter_website_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='urls',
        ),
        migrations.AddField(
            model_name='url',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopifyScrapper.website'),
        ),
    ]
