# Generated by Django 4.0.6 on 2022-07-17 08:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyScrapper', '0005_remove_website_urls_url_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('retailer', models.CharField(max_length=30)),
                ('direct_link', models.CharField(max_length=150)),
                ('auto_checkout_link', models.CharField(max_length=150)),
                ('stock_code', models.CharField(max_length=10)),
                ('size', models.ManyToManyField(to='ShopifyScrapper.size')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopifyScrapper.website')),
            ],
        ),
    ]
