# Generated by Django 4.0.6 on 2022-07-17 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyScrapper', '0006_size_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
